# Generated by Django 5.1.7 on 2025-03-15 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_location_event_price_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(default='1:45'),
        ),
    ]
